name: Deploy (prod)

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy_api_gateway:
    if: >-
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'main'
      }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy api-gateway
        run: flyctl deploy --remote-only -c packages/api-gateway/fly.toml .
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_GATEWAY_TOKEN }}

  deploy_auth_microservice:
    if: >-
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'main'
      }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy auth-microsservice
        run: flyctl deploy --remote-only -c packages/auth-microsservice/fly.toml .
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_AUTH_MICROSSERVICE_TOKEN }}
