name: Deploy (prod)

on:
  push:
    branches: [main]

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy_api_gateway:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy api-gateway
        run: flyctl deploy --remote-only --config ./packages/api-gateway/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_GATEWAY_TOKEN }}

  deploy_auth_microservice:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy auth-microsservice
        run: flyctl deploy --remote-only --config ./packages/auth-microsservice/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_AUTH_MICROSSERVICE_TOKEN }}
